### ISSUE TITLE
Who to talk to regarding this project?

### ISSUE THREAD

**Issue by kirkbushell** [flesh-cube/flesh-and-blood-cards#112]
Over on the FaB DB discord we have been discussing for some time setting up a FABJSON project, but that has grown - you can see much of our discussions and planning here: https://github.com/Cardtech-io/fabjson-data/discussions/1

However, seems this project is doing a lot already that would cover most of the points we were looking to do there. I can also see actually that quite a bit of card data came from FaB DB - at least initially ;)

I think there's far more we can do when opening up to the community like this, as you have done. I do wonder if there's an opportunity to work together, merge and/or build on each other's work.

So reach out to me on our discord: 

Let's chat :)

https://discord.gg/fWDrjr3geM

**Comment by kirkbushell** [comment]
> Haha, actually never used FaB DB for the card data to ensure it was fully open sourced - it was all transcribed by hand by using the official gallery pages, release notes, and LSS' CSVs :)
> 
> I'm relatively pleased with the current state of this repo, but there's still definitely more to be done (as evidenced by the issues I have open!) - if you or anyone else on your Discord has any feature requests or wants to discuss the data set, swing on by and open an issue here like you just did, so that the community can discuss it!

You sure about that? Because many of the cards have formatting that are found only on FaB DB, which I and a few others (paid to do so) setup to provide nicer formatting on FaB DB. It's a dead giveaway.

Regardless, I don't care - looking to support this project and/or combine ideas via a similar project, as we're looking to open source the data anyway :)

Are you getting much input to help on card data.etc? And what are your thoughts on setting up a graph ql API for the data, along with various download/output options? (such as yaml, json.etc.)

**Comment by luceleaftea** [comment]
If you are talking about the functional text being formatted using Markdown, yes, I added Markdown to all the text of the cards by hand. :)

Pretty much all of the transcribing has been done by me, but misspellings and wrong data have been caught and submitted by other users!

I have no interest in setting up a central API to be honest, because the intent of the repo is to allow people to fork the repo and use the data as they see fit instead of relying on a centrally hosted API. The repo has a script for spinning up an SQL database for people to get started on projects with easily, and JSON download through the static site [here](https://flesh-cube.github.io/flesh-and-blood-cards/) for any who would prefer that! YAML is definitely a good idea though 🤔 

In regards to combining ideas or support, feel free to make suggestions!

**Comment by kirkbushell** [comment]
I think you answere it all. haha

Patreon so I can support you? Manual updates are a LOT of work! And if you're going to continue doing so, I'd rather contribute where I can and just use this data, if that's alright :)

**Comment by luceleaftea** [comment]
Hm, I suppose a Patreon could be an option? I'd have to think about it, since I dunno if it would violate the spirit of open source 🤔 But of course, the repo is free to use for anyone, use it how you'd like! If you have any bugfixes you find, just open a PR and I'll make any comments on edits that are needed.

**Comment by kirkbushell** [comment]
Most open source project have supporter/donation options. Do look into it, let me know once you have it open. hehe

**Comment by luceleaftea** [comment]
Will do!

**Comment by HarrisonTotty** [comment]
I know this was closed but I just wanted to pop in and say how awesome it is to see the FaB techie community come together to build cool stuff!
